name: Build LaTeX document and release PDF

on:
  push:
    tags: "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

      - name: Release PDF file to [tag]
        uses: softprops/action-gh-release@v2.1.0
        with:
          name: ${{github.ref_name}}
          tag_name: ${{github.ref_name}}
          make_latest: true
          files: main.pdf

      - name: Release PDF file to [latest]
        uses: softprops/action-gh-release@v2.1.0
        with:
          name: Latest PDF release
          tag_name: latest
          files: main.pdf
